# Generated by Django 2.2.6 on 2019-12-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('photoUrl', models.CharField(max_length=100)),
                ('videoUrl', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('datePublished', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
