# Generated by Django 2.2.6 on 2019-12-20 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='photoUrl',
            new_name='imageUrl',
        ),
    ]
